- repo: git@github.com:pre-commit/pre-commit-hooks
  sha: v0.9.2
  hooks:
    - id: check-case-conflict
    - id: fix-encoding-pragma
    - id: check-docstring-first
    - id: trailing-whitespace
    - id: end-of-file-fixer
